title: Jonathan Conley
author: Jonathan Conley
email: conley.jj@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  Jonathan Conley's software portfolio.

# Header Links
homepage: http://127.0.0.1:4000
twitter_username: 
github_username:  jconley88
linkedin_username: jconley88


# Build settings
theme: jekyll-theme-portfolio

carousel_interval: 6000

plugins:
 - jekyll-feed
 - jekyll-seo-tag

exclude: [README.md, LICENSE.md, jekyll-portfolio.gemspec, update_bootstrap.sh]
